name: default
version: master-latest-unvalidated
providers:
  kubernetes:
    enabled: true
    accounts:
    - name: k8s
      providerVersion: 2
      context: spinnaker
      configureImagePullSecrets: true
      cacheThreads: 1
      omitNamespaces:
      - default
      - kube-public
      - kube-system
      - docs-site-v1
      kubeconfigFile: /var/secrets/k8s-kubeconfig
      checkPermissionsOnStartup: true
    primaryAccount: k8s
  appengine:
    enabled: true
    accounts:
      - name: my-appengine-account
        project: spinnaker-maggie
        jsonPath: /var/secrets/appengine-account.json
        sshTrustUnknownHosts: true
    primaryAccount: my-appengine-account
  google:
    enabled: true
    accounts:
      - name: my-gce-account
        project: spinnaker-maggie
        jsonPath: /var/secrets/gce-account.json
        alphaListed: true
        consul:
          enabled: true
          agentEndpoint: localhost
          agentPort: 8500
          datacenters: []
        regions:
          - us-east1-b
    primaryAccount: my-gce-account
    bakeryDefaults:
      templateFile: gce.json
      baseImages:
        - baseImage:
            id: my-image-id
            shortDescription: my short description
            detailedDescription: my detailed description
            imageFamily: true
          virtualizationSettings:
            sourceImage: my-source-image
            sourceImageFamily: my-source-image-family
      zone: us-central1-f
      network: default
      networkProjectId: my-network-project-id
      useInternalIp: true
  aws:
    enabled: true
    accounts:
      - name: my-aws-account
        environment: env
        defaultKeyPair: keyPair
        edda: edda
        discovery: discovery
        accountId: id
        regions:
          - name: myregion
        assumeRole: role
        lifecycleHooks:
          - defaultResult: ABANDON
            heartbeatTimeout: 12
            lifecycleTransition: autoscaling:EC2_INSTANCE_TERMINATING
            notificationTargetARN: arn:aws:sns:{{region}}:{{accountId}}:term-targ
            roleARN: arn:aws:iam::{{accountId}}:role-arn
    primaryAccount: my-aws-account
    bakeryDefaults:
      templateFile: file
      baseImages:
      - baseImage:
          id: my-image-id
          shortDescription: my short description
          detailedDescription: my detailed description
        virtualizationSettings:
          sourceAmi: my-source-ami
          virtualizationType: pv
      awsAccessKey: key
      awsSecretKey: keysecret
      awsSubnetId: subnetid
      awsVpcId: vpcid
      awsAssociatePublicIpAddress: true
      defaultVirtualizationType: pv
    defaultKeyPairTemplate: '{{name}}-keypair'
    defaultRegions:
      - name: us-west-2
    defaults:
      iamRole: BaseIAMRole
  cloudfoundry:
    enabled: true
    accounts:
      - name: my-cf-account
        environment: dev
        requiredGroupMembership: []
        permissions: {}
        password: pw
        user: username
        skipSslValidation: true
        api: api.sys.somesystem.com
        appsManagerUri: https://apps.sys.somesystem.com
        metricsUri: https://metrics.sys.somesystem.com
    primaryAccount: my-cf-account

persistentStorage:
  persistentStoreType: gcs
  azs: {}
  gcs:
    project: ezimanyi-spinnaker-dev
    bucket: ezimanyi-spinnaker-dev-pipelines
    rootFolder: front50
    bucketLocation: us
  redis: {}
  s3:
    rootFolder: front50
  oracle: {}
